### ISSUE TITLE
Modify staging workflow to work with fork

### ISSUE THREAD

**Issue by cderv** [rstudio/bookdown.org#79]
Following discussion in https://github.com/rstudio/bookdown.org/pull/76#discussion_r592430549, I tested with fork.

Currently it does not work with fork, https://github.com/rstudio/bookdown.org/pull/78/checks?check_run_id=2088425419

It seems to be an open feature request in https://github.com/actions/checkout/issues/455

I have another strategy in mind to make it work.

**Comment by cderv** [comment]
One solution could be inspired by https://github.com/r-lib/actions/tree/master/examples#commands-workflow
Special actions were developed to make fetch from / push to PRs, this could help us here. 

It would require a two step process: 
* Workflow is run on pull request to show the diff in CI
* If we validate, we add an issue comment (like `/unstage`) to run a process that would pull the PR, do some changes, commit the changes and push them to the PR.

I'll look more into how actions/checkout work for PR because that is the think which is not working as expected.

**Comment by cderv** [comment]
I am thinking that by doing a 
````yaml
	    - name: Clone repository
	      uses: actions/checkout@v2
	      with:
	        fetch-depth: 0
	        ref: ${{github.event.pull_request.head.ref}}
	        repository: ${{github.event.pull_request.head.repo.full_name}}
````
and using another GITHUB_PAT from one of us with the correct scope, it would work. 

It is possible that the default github.token does not have the correct scope (for security)
